### ISSUE TITLE
export option

### ISSUE THREAD

**Issue by darkworks** [tracespace/viewer#16] opened 2016-09-19 12:38 UTC
nice viewer but export option for svg will be good , so that renderings can be exported to svg downloadable files

thanks

**Comment by mcous** [comment] 2016-09-19 13:20
Hey, thanks for the feedback! Definitely want to add SVG downloading, just haven't had much free time to work on the site.

This is a duplicate of #9, so I'm gonna close this issue in favor of that one.

**Closed as completed by mcous** 2016-09-19 13:20 UTC

**Comment by darkworks** [comment] 2016-09-19 13:47
one more thing , can you tell me how can i install it on my local host or server so that i can work on its svg export feature , am not familiar with these webpacks type of apps ... so little instruction of how to install it for those who have no experience with webpacks will be good , so that i can have live copy of my local machine so that i can add few features to it 

thanks

**Comment by mcous** [comment] 2016-09-19 13:55
You'll need to install Node.js v6 (if you haven't already), and then:
1. `$ git clone git@github.com:tracespace/viewer.git`
2. `$ cd viewer`
3. `$ npm install`
4. `$ npm start`

At this point you'll be running a dev server listening on http://localhost:8080 (as detailed in https://github.com/tracespace/viewer#contributing).

To be completely honest (and before you sink too much time into it): I have a very specific idea of how I want this feature to be implemented, so please know that I'm unlikely to accept a PR for this feature.

**Comment by darkworks** [comment] 2016-09-19 14:25
ok no problem :)
